Repository jwarczynski/BuildingInfo, pull requests merged in 2022-12, with the labels that each got.

#5 documentation for model classes (Building, Floor, Room)
  pom.xml
  src/main/java/pl/put/poznan/buildingInfo/logic/locations/Building.java
  src/main/java/pl/put/poznan/buildingInfo/logic/locations/Floor.java
  src/main/java/pl/put/poznan/buildingInfo/logic/locations/Room.java
Labels: documentation

#7 LightPower and Volume endpoints + hotfix LightVisitor
  src/main/java/pl/put/poznan/buildingInfo/logic/visitors/LightVisitor.java
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: bug, enhancement

#8 Added json responses
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: enhancement

#10 logowanie na poziomie debug i info
  src/main/java/pl/put/poznan/buildingInfo/logic/visitors/LightVisitor.java
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
  src/main/resources/application.properties
Labels: enhancement

#11 Build jar pom modification
  README.md
  dependency-reduced-pom.xml
  pom.xml
Labels: enhancement

#13 Updated pom version
  pom.xml
Labels: documentation
