Repository jwarczynski/BuildingInfo, pull requests merged in 2023-01, with the labels that each got.

#21 Feature/testing
  src/test/java/pl/put/poznan/buildingInfo/logic/locations/BuildingTest.java
  src/test/java/pl/put/poznan/buildingInfo/logic/locations/FloorTest.java
  src/test/java/pl/put/poznan/buildingInfo/logic/locations/RoomTest.java
  src/test/java/pl/put/poznan/buildingInfo/logic/visitors/AreaVisitorTest.java
  src/test/java/pl/put/poznan/buildingInfo/logic/visitors/CubatureVisitorTest.java
  src/test/java/pl/put/poznan/buildingInfo/logic/visitors/LightVisitorTest.java
Labels: SP2, test

#23 HeatVisitor and Heat by Cubature endpoints
  src/main/java/pl/put/poznan/buildingInfo/logic/visitors/HeatVisitor.java
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: enhancement

#24 Rooms with over limit heating
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: enhancement, SP2

#29 Fixed and optimized heat endpoints
  src/main/java/pl/put/poznan/buildingInfo/logic/visitors/HeatVisitor.java
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: bug, SP2

#27 Avarage heat on floor or building
  src/main/java/pl/put/poznan/buildingInfo/logic/visitors/AvarageHeatVisitor.java
  src/main/java/pl/put/poznan/buildingInfo/rest/BuildingInfoRestController.java
Labels: enhancement, SP2

#31 Updated version to 1.1.0
  pom.xml
Labels: SP2
